//services/user/proto/user.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: user.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ================= Enums =================
type UserStatusEnum int32

const (
	UserStatusEnum_STATUS_UNSPECIFIED UserStatusEnum = 0
	UserStatusEnum_ACTIVE             UserStatusEnum = 1
	UserStatusEnum_SUSPENDED          UserStatusEnum = 2
	UserStatusEnum_PENDING            UserStatusEnum = 3
	UserStatusEnum_CLOSED             UserStatusEnum = 4
)

// Enum value maps for UserStatusEnum.
var (
	UserStatusEnum_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "ACTIVE",
		2: "SUSPENDED",
		3: "PENDING",
		4: "CLOSED",
	}
	UserStatusEnum_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"ACTIVE":             1,
		"SUSPENDED":          2,
		"PENDING":            3,
		"CLOSED":             4,
	}
)

func (x UserStatusEnum) Enum() *UserStatusEnum {
	p := new(UserStatusEnum)
	*p = x
	return p
}

func (x UserStatusEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatusEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[0].Descriptor()
}

func (UserStatusEnum) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[0]
}

func (x UserStatusEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatusEnum.Descriptor instead.
func (UserStatusEnum) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

// ================= Input Structures =================
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *RegistrationRequest   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetUser() *RegistrationRequest {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserBySSOIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SsoId         string                 `protobuf:"bytes,1,opt,name=sso_id,json=ssoId,proto3" json:"sso_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBySSOIDRequest) Reset() {
	*x = GetUserBySSOIDRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBySSOIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBySSOIDRequest) ProtoMessage() {}

func (x *GetUserBySSOIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBySSOIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserBySSOIDRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserBySSOIDRequest) GetSsoId() string {
	if x != nil {
		return x.SsoId
	}
	return ""
}

type GetUserForAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserForAuthRequest) Reset() {
	*x = GetUserForAuthRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserForAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserForAuthRequest) ProtoMessage() {}

func (x *GetUserForAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserForAuthRequest.ProtoReflect.Descriptor instead.
func (*GetUserForAuthRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserForAuthRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	User          *UserInput             `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRequest) GetUser() *UserInput {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateUserRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type RegistrationRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	FirstName string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email     string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// Types that are valid to be assigned to AuthMethod:
	//
	//	*RegistrationRequest_Password
	//	*RegistrationRequest_SsoId
	AuthMethod    isRegistrationRequest_AuthMethod `protobuf_oneof:"auth_method"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *RegistrationRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegistrationRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegistrationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegistrationRequest) GetAuthMethod() isRegistrationRequest_AuthMethod {
	if x != nil {
		return x.AuthMethod
	}
	return nil
}

func (x *RegistrationRequest) GetPassword() string {
	if x != nil {
		if x, ok := x.AuthMethod.(*RegistrationRequest_Password); ok {
			return x.Password
		}
	}
	return ""
}

func (x *RegistrationRequest) GetSsoId() string {
	if x != nil {
		if x, ok := x.AuthMethod.(*RegistrationRequest_SsoId); ok {
			return x.SsoId
		}
	}
	return ""
}

type isRegistrationRequest_AuthMethod interface {
	isRegistrationRequest_AuthMethod()
}

type RegistrationRequest_Password struct {
	Password string `protobuf:"bytes,4,opt,name=password,proto3,oneof"` // Only for non-SSO
}

type RegistrationRequest_SsoId struct {
	SsoId string `protobuf:"bytes,5,opt,name=sso_id,json=ssoId,proto3,oneof"` // For SSO users
}

func (*RegistrationRequest_Password) isRegistrationRequest_AuthMethod() {}

func (*RegistrationRequest_SsoId) isRegistrationRequest_AuthMethod() {}

type UserInput struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	FirstName string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email     string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// Types that are valid to be assigned to AuthMethod:
	//
	//	*UserInput_Password
	//	*UserInput_SsoId
	AuthMethod    isUserInput_AuthMethod `protobuf_oneof:"auth_method"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInput) Reset() {
	*x = UserInput{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInput) ProtoMessage() {}

func (x *UserInput) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInput.ProtoReflect.Descriptor instead.
func (*UserInput) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserInput) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserInput) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInput) GetAuthMethod() isUserInput_AuthMethod {
	if x != nil {
		return x.AuthMethod
	}
	return nil
}

func (x *UserInput) GetPassword() string {
	if x != nil {
		if x, ok := x.AuthMethod.(*UserInput_Password); ok {
			return x.Password
		}
	}
	return ""
}

func (x *UserInput) GetSsoId() string {
	if x != nil {
		if x, ok := x.AuthMethod.(*UserInput_SsoId); ok {
			return x.SsoId
		}
	}
	return ""
}

type isUserInput_AuthMethod interface {
	isUserInput_AuthMethod()
}

type UserInput_Password struct {
	Password string `protobuf:"bytes,4,opt,name=password,proto3,oneof"` // Only for non-SSO
}

type UserInput_SsoId struct {
	SsoId string `protobuf:"bytes,5,opt,name=sso_id,json=ssoId,proto3,oneof"` // For SSO users
}

func (*UserInput_Password) isUserInput_AuthMethod() {}

func (*UserInput_SsoId) isUserInput_AuthMethod() {}

// ================= Output Structures =================
type CreateUserResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // external_id as a string
	FirstName       string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName        string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Status          UserStatusEnum         `protobuf:"varint,4,opt,name=status,proto3,enum=user.UserStatusEnum" json:"status,omitempty"`
	Email           string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	TermsAcceptedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=terms_accepted_at,json=termsAcceptedAt,proto3" json:"terms_accepted_at,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *CreateUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateUserResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateUserResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateUserResponse) GetStatus() UserStatusEnum {
	if x != nil {
		return x.Status
	}
	return UserStatusEnum_STATUS_UNSPECIFIED
}

func (x *CreateUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserResponse) GetTermsAcceptedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TermsAcceptedAt
	}
	return nil
}

func (x *CreateUserResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetUserResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // external_id
	FirstName       string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName        string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Status          UserStatusEnum         `protobuf:"varint,4,opt,name=status,proto3,enum=user.UserStatusEnum" json:"status,omitempty"`
	Email           string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	TermsAcceptedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=terms_accepted_at,json=termsAcceptedAt,proto3" json:"terms_accepted_at,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GetUserResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *GetUserResponse) GetStatus() UserStatusEnum {
	if x != nil {
		return x.Status
	}
	return UserStatusEnum_STATUS_UNSPECIFIED
}

func (x *GetUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserResponse) GetTermsAcceptedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TermsAcceptedAt
	}
	return nil
}

func (x *GetUserResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetUserResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type AuthUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"` // Empty for SSO users
	Status        UserStatusEnum         `protobuf:"varint,3,opt,name=status,proto3,enum=user.UserStatusEnum" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthUserResponse) Reset() {
	*x = AuthUserResponse{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserResponse) ProtoMessage() {}

func (x *AuthUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserResponse.ProtoReflect.Descriptor instead.
func (*AuthUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *AuthUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthUserResponse) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *AuthUserResponse) GetStatus() UserStatusEnum {
	if x != nil {
		return x.Status
	}
	return UserStatusEnum_STATUS_UNSPECIFIED
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*GetUserResponse     `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *ListUsersResponse) GetUsers() []*GetUserResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateUserResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // external_id
	FirstName       string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName        string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Status          UserStatusEnum         `protobuf:"varint,4,opt,name=status,proto3,enum=user.UserStatusEnum" json:"status,omitempty"`
	Email           string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	TermsAcceptedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=terms_accepted_at,json=termsAcceptedAt,proto3" json:"terms_accepted_at,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateUserResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateUserResponse) GetStatus() UserStatusEnum {
	if x != nil {
		return x.Status
	}
	return UserStatusEnum_STATUS_UNSPECIFIED
}

func (x *UpdateUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserResponse) GetTermsAcceptedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TermsAcceptedAt
	}
	return nil
}

func (x *UpdateUserResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UpdateUserResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ================= Shared Messages =================
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	StatusFilter  *UserStatusEnum        `protobuf:"varint,3,opt,name=status_filter,json=statusFilter,proto3,enum=user.UserStatusEnum,oneof" json:"status_filter,omitempty"`
	NameFilter    *string                `protobuf:"bytes,4,opt,name=name_filter,json=nameFilter,proto3,oneof" json:"name_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListUsersRequest) GetStatusFilter() UserStatusEnum {
	if x != nil && x.StatusFilter != nil {
		return *x.StatusFilter
	}
	return UserStatusEnum_STATUS_UNSPECIFIED
}

func (x *ListUsersRequest) GetNameFilter() string {
	if x != nil && x.NameFilter != nil {
		return *x.NameFilter
	}
	return ""
}

type UserCompliance struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	User              *CreateUserResponse    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Consent           *UserConsentHistory    `protobuf:"bytes,2,opt,name=consent,proto3" json:"consent,omitempty"`
	AddressValidation *AddressCompliance     `protobuf:"bytes,3,opt,name=address_validation,json=addressValidation,proto3" json:"address_validation,omitempty"`
	Audits            *AuditInfo             `protobuf:"bytes,4,opt,name=audits,proto3" json:"audits,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserCompliance) Reset() {
	*x = UserCompliance{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCompliance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCompliance) ProtoMessage() {}

func (x *UserCompliance) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCompliance.ProtoReflect.Descriptor instead.
func (*UserCompliance) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *UserCompliance) GetUser() *CreateUserResponse {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserCompliance) GetConsent() *UserConsentHistory {
	if x != nil {
		return x.Consent
	}
	return nil
}

func (x *UserCompliance) GetAddressValidation() *AddressCompliance {
	if x != nil {
		return x.AddressValidation
	}
	return nil
}

func (x *UserCompliance) GetAudits() *AuditInfo {
	if x != nil {
		return x.Audits
	}
	return nil
}

type AddressCompliance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsVerified    bool                   `protobuf:"varint,1,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	VerifiedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressCompliance) Reset() {
	*x = AddressCompliance{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressCompliance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressCompliance) ProtoMessage() {}

func (x *AddressCompliance) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressCompliance.ProtoReflect.Descriptor instead.
func (*AddressCompliance) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *AddressCompliance) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *AddressCompliance) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

type UserConsentHistory struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DataConsentVersion string                 `protobuf:"bytes,1,opt,name=data_consent_version,json=dataConsentVersion,proto3" json:"data_consent_version,omitempty"`
	TermsAcceptedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=terms_accepted_at,json=termsAcceptedAt,proto3" json:"terms_accepted_at,omitempty"`
	ConsentUpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=consent_updated_at,json=consentUpdatedAt,proto3,oneof" json:"consent_updated_at,omitempty"`
	ConsentWithdrawnAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=consent_withdrawn_at,json=consentWithdrawnAt,proto3,oneof" json:"consent_withdrawn_at,omitempty"`
	AnonymizedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=anonymized_at,json=anonymizedAt,proto3,oneof" json:"anonymized_at,omitempty"`
	// Soft Delete and Reactivation tracking if done prior to expiry of GDPR compliance timeframe
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	ReactivatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=reactivated_at,json=reactivatedAt,proto3,oneof" json:"reactivated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserConsentHistory) Reset() {
	*x = UserConsentHistory{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserConsentHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConsentHistory) ProtoMessage() {}

func (x *UserConsentHistory) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConsentHistory.ProtoReflect.Descriptor instead.
func (*UserConsentHistory) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *UserConsentHistory) GetDataConsentVersion() string {
	if x != nil {
		return x.DataConsentVersion
	}
	return ""
}

func (x *UserConsentHistory) GetTermsAcceptedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TermsAcceptedAt
	}
	return nil
}

func (x *UserConsentHistory) GetConsentUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConsentUpdatedAt
	}
	return nil
}

func (x *UserConsentHistory) GetConsentWithdrawnAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConsentWithdrawnAt
	}
	return nil
}

func (x *UserConsentHistory) GetAnonymizedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AnonymizedAt
	}
	return nil
}

func (x *UserConsentHistory) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *UserConsentHistory) GetReactivatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReactivatedAt
	}
	return nil
}

type AuditInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	ModifiedBy    []string               `protobuf:"bytes,3,rep,name=modified_by,json=modifiedBy,proto3" json:"modified_by,omitempty"` // User IDs or system actors
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditInfo) Reset() {
	*x = AuditInfo{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditInfo) ProtoMessage() {}

func (x *AuditInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditInfo.ProtoReflect.Descriptor instead.
func (*AuditInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *AuditInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AuditInfo) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *AuditInfo) GetModifiedBy() []string {
	if x != nil {
		return x.ModifiedBy
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\"B\n" +
	"\x11CreateUserRequest\x12-\n" +
	"\x04user\x18\x01 \x01(\v2\x19.user.RegistrationRequestR\x04user\".\n" +
	"\x15GetUserBySSOIDRequest\x12\x15\n" +
	"\x06sso_id\x18\x01 \x01(\tR\x05ssoId\"-\n" +
	"\x15GetUserForAuthRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x8e\x01\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\x04user\x18\x02 \x01(\v2\x0f.user.UserInputR\x04user\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\xad\x01\n" +
	"\x13RegistrationRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1c\n" +
	"\bpassword\x18\x04 \x01(\tH\x00R\bpassword\x12\x17\n" +
	"\x06sso_id\x18\x05 \x01(\tH\x00R\x05ssoIdB\r\n" +
	"\vauth_method\"\xa3\x01\n" +
	"\tUserInput\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1c\n" +
	"\bpassword\x18\x04 \x01(\tH\x00R\bpassword\x12\x17\n" +
	"\x06sso_id\x18\x05 \x01(\tH\x00R\x05ssoIdB\r\n" +
	"\vauth_method\"\xa7\x02\n" +
	"\x12CreateUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12,\n" +
	"\x06status\x18\x04 \x01(\x0e2\x14.user.UserStatusEnumR\x06status\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12F\n" +
	"\x11terms_accepted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0ftermsAcceptedAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xf3\x02\n" +
	"\x0fGetUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12,\n" +
	"\x06status\x18\x04 \x01(\x0e2\x14.user.UserStatusEnumR\x06status\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12F\n" +
	"\x11terms_accepted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0ftermsAcceptedAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tupdatedAt\x88\x01\x01B\r\n" +
	"\v_updated_at\"u\n" +
	"\x10AuthUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\x12,\n" +
	"\x06status\x18\x03 \x01(\x0e2\x14.user.UserStatusEnumR\x06status\"h\n" +
	"\x11ListUsersResponse\x12+\n" +
	"\x05users\x18\x01 \x03(\v2\x15.user.GetUserResponseR\x05users\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xf6\x02\n" +
	"\x12UpdateUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12,\n" +
	"\x06status\x18\x04 \x01(\x0e2\x14.user.UserStatusEnumR\x06status\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12F\n" +
	"\x11terms_accepted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0ftermsAcceptedAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tupdatedAt\x88\x01\x01B\r\n" +
	"\v_updated_at\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xd6\x01\n" +
	"\x10ListUsersRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12>\n" +
	"\rstatus_filter\x18\x03 \x01(\x0e2\x14.user.UserStatusEnumH\x00R\fstatusFilter\x88\x01\x01\x12$\n" +
	"\vname_filter\x18\x04 \x01(\tH\x01R\n" +
	"nameFilter\x88\x01\x01B\x10\n" +
	"\x0e_status_filterB\x0e\n" +
	"\f_name_filter\"\xe3\x01\n" +
	"\x0eUserCompliance\x12,\n" +
	"\x04user\x18\x01 \x01(\v2\x18.user.CreateUserResponseR\x04user\x122\n" +
	"\aconsent\x18\x02 \x01(\v2\x18.user.UserConsentHistoryR\aconsent\x12F\n" +
	"\x12address_validation\x18\x03 \x01(\v2\x17.user.AddressComplianceR\x11addressValidation\x12'\n" +
	"\x06audits\x18\x04 \x01(\v2\x0f.user.AuditInfoR\x06audits\"q\n" +
	"\x11AddressCompliance\x12\x1f\n" +
	"\vis_verified\x18\x01 \x01(\bR\n" +
	"isVerified\x12;\n" +
	"\vverified_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt\"\xe2\x04\n" +
	"\x12UserConsentHistory\x120\n" +
	"\x14data_consent_version\x18\x01 \x01(\tR\x12dataConsentVersion\x12F\n" +
	"\x11terms_accepted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0ftermsAcceptedAt\x12M\n" +
	"\x12consent_updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x10consentUpdatedAt\x88\x01\x01\x12Q\n" +
	"\x14consent_withdrawn_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x12consentWithdrawnAt\x88\x01\x01\x12D\n" +
	"\ranonymized_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\fanonymizedAt\x88\x01\x01\x12>\n" +
	"\n" +
	"deleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\tdeletedAt\x88\x01\x01\x12F\n" +
	"\x0ereactivated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x04R\rreactivatedAt\x88\x01\x01B\x15\n" +
	"\x13_consent_updated_atB\x17\n" +
	"\x15_consent_withdrawn_atB\x10\n" +
	"\x0e_anonymized_atB\r\n" +
	"\v_deleted_atB\x11\n" +
	"\x0f_reactivated_at\"\xa6\x01\n" +
	"\tAuditInfo\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\flast_updated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12\x1f\n" +
	"\vmodified_by\x18\x03 \x03(\tR\n" +
	"modifiedBy*\\\n" +
	"\x0eUserStatusEnum\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\r\n" +
	"\tSUSPENDED\x10\x02\x12\v\n" +
	"\aPENDING\x10\x03\x12\n" +
	"\n" +
	"\x06CLOSED\x10\x042\xde\x04\n" +
	"\vUserService\x12?\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\x18.user.CreateUserResponse\x12:\n" +
	"\vGetUserByID\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x12D\n" +
	"\x0eGetUserBySSOID\x12\x1b.user.GetUserBySSOIDRequest\x1a\x15.user.GetUserResponse\x12E\n" +
	"\x0eGetUserForAuth\x12\x1b.user.GetUserForAuthRequest\x1a\x16.user.AuthUserResponse\x12<\n" +
	"\tListUsers\x12\x16.user.ListUsersRequest\x1a\x17.user.ListUsersResponse\x12?\n" +
	"\n" +
	"UpdateUser\x12\x17.user.UpdateUserRequest\x1a\x18.user.UpdateUserResponse\x12=\n" +
	"\n" +
	"DeleteUser\x12\x17.user.DeleteUserRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\x14GetUserForCompliance\x12\x14.user.GetUserRequest\x1a\x14.user.UserCompliance\x12C\n" +
	"\x11GetConsentHistory\x12\x14.user.GetUserRequest\x1a\x18.user.UserConsentHistoryB6Z4github.com/adammwaniki/wateja/services/user/genprotob\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_user_proto_goTypes = []any{
	(UserStatusEnum)(0),           // 0: user.UserStatusEnum
	(*CreateUserRequest)(nil),     // 1: user.CreateUserRequest
	(*GetUserBySSOIDRequest)(nil), // 2: user.GetUserBySSOIDRequest
	(*GetUserForAuthRequest)(nil), // 3: user.GetUserForAuthRequest
	(*UpdateUserRequest)(nil),     // 4: user.UpdateUserRequest
	(*RegistrationRequest)(nil),   // 5: user.RegistrationRequest
	(*UserInput)(nil),             // 6: user.UserInput
	(*CreateUserResponse)(nil),    // 7: user.CreateUserResponse
	(*GetUserResponse)(nil),       // 8: user.GetUserResponse
	(*AuthUserResponse)(nil),      // 9: user.AuthUserResponse
	(*ListUsersResponse)(nil),     // 10: user.ListUsersResponse
	(*UpdateUserResponse)(nil),    // 11: user.UpdateUserResponse
	(*GetUserRequest)(nil),        // 12: user.GetUserRequest
	(*DeleteUserRequest)(nil),     // 13: user.DeleteUserRequest
	(*ListUsersRequest)(nil),      // 14: user.ListUsersRequest
	(*UserCompliance)(nil),        // 15: user.UserCompliance
	(*AddressCompliance)(nil),     // 16: user.AddressCompliance
	(*UserConsentHistory)(nil),    // 17: user.UserConsentHistory
	(*AuditInfo)(nil),             // 18: user.AuditInfo
	(*fieldmaskpb.FieldMask)(nil), // 19: google.protobuf.FieldMask
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 21: google.protobuf.Empty
}
var file_user_proto_depIdxs = []int32{
	5,  // 0: user.CreateUserRequest.user:type_name -> user.RegistrationRequest
	6,  // 1: user.UpdateUserRequest.user:type_name -> user.UserInput
	19, // 2: user.UpdateUserRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 3: user.CreateUserResponse.status:type_name -> user.UserStatusEnum
	20, // 4: user.CreateUserResponse.terms_accepted_at:type_name -> google.protobuf.Timestamp
	20, // 5: user.CreateUserResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 6: user.GetUserResponse.status:type_name -> user.UserStatusEnum
	20, // 7: user.GetUserResponse.terms_accepted_at:type_name -> google.protobuf.Timestamp
	20, // 8: user.GetUserResponse.created_at:type_name -> google.protobuf.Timestamp
	20, // 9: user.GetUserResponse.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 10: user.AuthUserResponse.status:type_name -> user.UserStatusEnum
	8,  // 11: user.ListUsersResponse.users:type_name -> user.GetUserResponse
	0,  // 12: user.UpdateUserResponse.status:type_name -> user.UserStatusEnum
	20, // 13: user.UpdateUserResponse.terms_accepted_at:type_name -> google.protobuf.Timestamp
	20, // 14: user.UpdateUserResponse.created_at:type_name -> google.protobuf.Timestamp
	20, // 15: user.UpdateUserResponse.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 16: user.ListUsersRequest.status_filter:type_name -> user.UserStatusEnum
	7,  // 17: user.UserCompliance.user:type_name -> user.CreateUserResponse
	17, // 18: user.UserCompliance.consent:type_name -> user.UserConsentHistory
	16, // 19: user.UserCompliance.address_validation:type_name -> user.AddressCompliance
	18, // 20: user.UserCompliance.audits:type_name -> user.AuditInfo
	20, // 21: user.AddressCompliance.verified_at:type_name -> google.protobuf.Timestamp
	20, // 22: user.UserConsentHistory.terms_accepted_at:type_name -> google.protobuf.Timestamp
	20, // 23: user.UserConsentHistory.consent_updated_at:type_name -> google.protobuf.Timestamp
	20, // 24: user.UserConsentHistory.consent_withdrawn_at:type_name -> google.protobuf.Timestamp
	20, // 25: user.UserConsentHistory.anonymized_at:type_name -> google.protobuf.Timestamp
	20, // 26: user.UserConsentHistory.deleted_at:type_name -> google.protobuf.Timestamp
	20, // 27: user.UserConsentHistory.reactivated_at:type_name -> google.protobuf.Timestamp
	20, // 28: user.AuditInfo.created_at:type_name -> google.protobuf.Timestamp
	20, // 29: user.AuditInfo.last_updated:type_name -> google.protobuf.Timestamp
	1,  // 30: user.UserService.CreateUser:input_type -> user.CreateUserRequest
	12, // 31: user.UserService.GetUserByID:input_type -> user.GetUserRequest
	2,  // 32: user.UserService.GetUserBySSOID:input_type -> user.GetUserBySSOIDRequest
	3,  // 33: user.UserService.GetUserForAuth:input_type -> user.GetUserForAuthRequest
	14, // 34: user.UserService.ListUsers:input_type -> user.ListUsersRequest
	4,  // 35: user.UserService.UpdateUser:input_type -> user.UpdateUserRequest
	13, // 36: user.UserService.DeleteUser:input_type -> user.DeleteUserRequest
	12, // 37: user.UserService.GetUserForCompliance:input_type -> user.GetUserRequest
	12, // 38: user.UserService.GetConsentHistory:input_type -> user.GetUserRequest
	7,  // 39: user.UserService.CreateUser:output_type -> user.CreateUserResponse
	8,  // 40: user.UserService.GetUserByID:output_type -> user.GetUserResponse
	8,  // 41: user.UserService.GetUserBySSOID:output_type -> user.GetUserResponse
	9,  // 42: user.UserService.GetUserForAuth:output_type -> user.AuthUserResponse
	10, // 43: user.UserService.ListUsers:output_type -> user.ListUsersResponse
	11, // 44: user.UserService.UpdateUser:output_type -> user.UpdateUserResponse
	21, // 45: user.UserService.DeleteUser:output_type -> google.protobuf.Empty
	15, // 46: user.UserService.GetUserForCompliance:output_type -> user.UserCompliance
	17, // 47: user.UserService.GetConsentHistory:output_type -> user.UserConsentHistory
	39, // [39:48] is the sub-list for method output_type
	30, // [30:39] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_user_proto_msgTypes[4].OneofWrappers = []any{
		(*RegistrationRequest_Password)(nil),
		(*RegistrationRequest_SsoId)(nil),
	}
	file_user_proto_msgTypes[5].OneofWrappers = []any{
		(*UserInput_Password)(nil),
		(*UserInput_SsoId)(nil),
	}
	file_user_proto_msgTypes[7].OneofWrappers = []any{}
	file_user_proto_msgTypes[10].OneofWrappers = []any{}
	file_user_proto_msgTypes[13].OneofWrappers = []any{}
	file_user_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		EnumInfos:         file_user_proto_enumTypes,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
